### ISSUE TITLE
Will there be a version compatible with 4.0 and if so when will it get released?

### ISSUE THREAD

**Issue by its-blue** [mrtripie/godot-string-keys#1]

**Comment by mrtripie** [comment]
Godot 4 adds a similar feature to this (POT file generation), so I'm not sure if updating this is needed. I haven't done a close look at it, but it does seem like there may be some advantages to using this addon over it though, and it probably won't be too time consuming to port, so I'll look into it when I port my game project to Godot 4 (which I think should be soon after the first beta).
